project_id = "tshvbtrnlcigronrgxtx"

[functions.balasinaja]
verify_jwt = false

[functions.send-broadcast]
verify_jwt = true

[functions.process-scheduled-broadcasts]
verify_jwt = false

[functions.send-subscription-notification]
verify_jwt = false

[functions.send-welcome-notification]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false